import {readFileSync,writeFileSync} from 'node:fs';
const p='site/public/index.html';
let h=readFileSync(p,'utf8');
if(!h.includes('</head>')) throw new Error('invalid index');
const marker='<meta name="okok-tetris-playable-v2" content="rollback-safe">';
if(!h.includes('okok-tetris-playable-v2')) h=h.replace('</head>',marker+'\n</head>');
writeFileSync(p,h);
// Preserve the unique deployment cache generated by gloss-build.
console.log('OKI layout restored; unsafe Tetris sizing disabled.');
